version: "3.9"
volumes:
    database:
services:
    app:
        build:
            context: ./
            dockerfile: Dockerfile
        ports: 
            - "8080:8080"
        container_name: printerstatus
        links:
            - mongo
        environment:
            - DEPLOY=docker
        command: node app.js
    mongo:
        image: mongo
        ports:
            - "27017:27017"
        container_name: mongo
        volumes:
            - database:/data/db


