services:
    app:
        build:
            context: ./
            dockerfile: Dockerfile
        ports: 
            - "8080:8080"
        container_name: printerstatus
        links:
            - database
        command: npm run prod
    database:
        image: mongo
        ports:
            - "27017:27017"
        container_name: mongo
        volumes:
            - ./db:/data/db:z
