version: "3.9"
volumes:
    database:
services:
    app:
        build:
            context: ./
            dockerfile: Dockerfile
        ports: 
            - "8030:80"
        container_name: printerstatus
        links:
            - mongo
        environment:
            - DEPLOY=docker
        volumes:
            - ./public/tables:/app/public/tables
            - ./logs:/app/logs
    mongo:
        image: mongo
        ports:
            - "27017:27017"
        container_name: mongo
        volumes:
            - database:/data/db

